export const CREATE_SUBREDDIT_SUCCESS = 'CREATE_SUBREDDIT_SUCCESS';
export const CREATE_SUBREDDIT_ERROR = 'CREATE_SUBREDDIT_ERROR';
export const GET_SUBREDDITS_SUCCESS = 'GET_SUBREDDITS_SUCCESS';
export const GET_SUBREDDITS_ERROR = 'GET_SUBREDDITS_ERROR';
export const GET_SUBREDDIT_SUCCESS = 'GET_SUBREDDIT_SUCCESS';
export const GET_SUBREDDIT_ERROR = 'GET_SUBREDDIT_ERROR';
export const DELETE_SUBREDDIT_SUCCESS = 'DELETE_SUBREDDIT_SUCCESS';
export const DELETE_SUBREDDIT_ERROR = 'DELETE_SUBREDDIT_ERROR';
