export const LOADING_COMMENTS = 'LOADING_COMMENTS';
export const SUBMIT_COMMENT_SUCCESS = 'SUBMIT_COMMENT_SUCCESS';
export const SUBMIT_COMMENT_ERROR = 'SUBMIT_COMMENT_ERROR';
export const FETCH_ALL_COMMENTS_SUCCESS = 'FETCH_ALL_COMMENTS_SUCCESS';
export const FETCH_ALL_COMMENTS_ERROR = 'FETCH_ALL_COMMENTS_ERROR';
